### ISSUE TITLE
PreVM does not update itself with a nextCluster update

### ISSUE THREAD

**Issue by DinoMarlir** [nextCluster/nextCluster#40]
After updating nextCluster, I had to manually update the PreVM at static services. Can this be automated?

**Comment by HabsGleich** [comment]
Hey, unfortunately, this is a docker-image "problem".
The static services can just be restarted to update the PreVM.
For the dynamic groups, just rebuild the images in the images folder to update the PreVM.
Only after a rebuild can the new PreVM be used.
