### ISSUE TITLE
Spieler joint mit der Proxy Ip-Adresse

### ISSUE THREAD

**Issue by Niklas326** [nextCluster/nextCluster#7]
Beim Betreten des Servers wird nicht die IP-Adresse des Spielers angezeigt, sondern die des Servers, auf dem nextCluster läuft. **Es könnte sich auch um eine fehlerhafte Konfiguration meinerseits handeln.**

velocity.toml: https://hastebin.com/share/qedacititi.ini

**Comment by DinoMarlir** [comment]
I have the same "error" so I guess it's not your fault.
